services:
  # Employee Workspace Service (workspace.ooak.photography)
  - type: web
    name: ooak-production
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm ci && npm run build:workspace
    startCommand: npm run start:workspace
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: NEXT_PUBLIC_APP_URL
        value: https://workspace.ooak.photography
      - key: DATABASE_URL
        fromDatabase:
          name: ooak-database
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: ooak-database
          property: connectionString
      - key: WHATSAPP_VERIFY_TOKEN
        value: whatsapp_verify_123
      - key: NEXTAUTH_SECRET
        value: mbBSSdwnS2UY9/F9WOyXigxlDFUqubjQFf5VnXrcWXE=
      - key: NEXTAUTH_URL
        value: https://workspace.ooak.photography
      - key: JWT_SECRET
        value: 5fh+rT0PoqFDLtrITHjyEnYYNUG4p2MTWu+QGhDgRbQ=
      - key: ENCRYPTION_KEY
        value: ldX6UIaAtxdFhCr3ZE4hBjh33fOD0UekAvjgU1xJe/8=
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    domains:
      - workspace.ooak.photography
    healthCheckPath: /api/health

  # WhatsApp API Service (api.ooak.photography)
  - type: web
    name: ooak-whatsapp-api
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm ci && npm run build:api
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_APP_URL
        value: https://api.ooak.photography
      - key: DATABASE_URL
        fromDatabase:
          name: ooak-database
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: ooak-database
          property: connectionString
      - key: WHATSAPP_VERIFY_TOKEN
        value: whatsapp_verify_123
      - key: NEXTAUTH_SECRET
        value: mbBSSdwnS2UY9/F9WOyXigxlDFUqubjQFf5VnXrcWXE=
      - key: NEXTAUTH_URL
        value: https://api.ooak.photography
      - key: JWT_SECRET
        value: 5fh+rT0PoqFDLtrITHjyEnYYNUG4p2MTWu+QGhDgRbQ=
      - key: ENCRYPTION_KEY
        value: ldX6UIaAtxdFhCr3ZE4hBjh33fOD0UekAvjgU1xJe/8=
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    domains:
      - api.ooak.photography
    healthCheckPath: /api/health

databases:
  - name: ooak-database
    databaseName: ooak_future_production
    user: ooak_user
    plan: starter
    region: oregon
