services:
  # Production Web Service
  - type: web
    name: ooak-production
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_BASE_URL
        generateValue: true
      - key: POSTGRES_HOST
        fromDatabase:
          name: ooak-database
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: ooak-database
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: ooak-database
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: ooak-database
          property: password
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: ooak-database
          property: database
      - key: DATABASE_URL
        fromDatabase:
          name: ooak-database
          property: connectionString
    domains:
      - workspace.ooak.photography
    healthCheckPath: /api/health

  # WhatsApp API Service
  - type: web
    name: ooak-whatsapp-api
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SERVICE_NAME
        value: whatsapp-automation
      - key: NEXT_PUBLIC_BASE_URL
        generateValue: true
      - key: POSTGRES_HOST
        fromDatabase:
          name: ooak-database
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: ooak-database
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: ooak-database
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: ooak-database
          property: password
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: ooak-database
          property: database
      - key: DATABASE_URL
        fromDatabase:
          name: ooak-database
          property: connectionString
    domains:
      - api.ooak.photography
    healthCheckPath: /api/health

databases:
  - name: ooak-database
    databaseName: ooak_future_production
    user: ooak_user
    plan: starter
