export interface MenuItem {
  id: number;
  parent_id?: number;
  name: string;
  description: string;
  icon: string;
  path: string;
  sort_order: number;
  is_visible: boolean;
  string_id: string;
  section_name?: string;
  is_admin_only: boolean;
  badge_text?: string;
  badge_variant: string;
  is_new: boolean;
  category: string;
  children?: MenuItem[];
}

export const menuData: MenuItem[] = [
  // Core Business Section
  {
    id: 1,
    name: "Core Business",
    description: "Essential business operations",
    icon: "LayoutGrid",
    path: "/core-business",
    sort_order: 1,
    is_visible: true,
    string_id: "core-business",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 2,
        parent_id: 1,
        name: "Dashboard",
        description: "Business overview",
        icon: "Home",
        path: "/dashboard",
        sort_order: 1,
        is_visible: true,
        string_id: "dashboard",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 3,
        parent_id: 1,
        name: "🚀 AI Business Control",
        description: "AI-powered business control",
        icon: "Cpu",
        path: "/ai-business-control",
        sort_order: 2,
        is_visible: true,
        string_id: "ai-control",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // Sales & Revenue Section
  {
    id: 4,
    name: "Sales & Revenue",
    description: "Sales and revenue management",
    icon: "DollarSign",
    path: "/sales",
    sort_order: 2,
    is_visible: true,
    string_id: "sales-revenue",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 5,
        parent_id: 4,
        name: "Sales Dashboard",
        description: "Sales performance overview",
        icon: "BarChart",
        path: "/sales/dashboard",
        sort_order: 1,
        is_visible: true,
        string_id: "sales-dashboard",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 6,
        parent_id: 4,
        name: "Create Lead",
        description: "Create new leads",
        icon: "UserPlus",
        path: "/sales/create-lead",
        sort_order: 2,
        is_visible: true,
        string_id: "sales-create-lead",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 7,
        parent_id: 4,
        name: "My Leads",
        description: "Personal lead management",
        icon: "Users",
        path: "/sales/my-leads",
        sort_order: 3,
        is_visible: true,
        string_id: "sales-my-leads",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 8,
        parent_id: 4,
        name: "Unassigned Leads",
        description: "Leads pending assignment",
        icon: "UserMinus",
        path: "/sales/unassigned",
        sort_order: 4,
        is_visible: true,
        string_id: "sales-unassigned-leads",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 9,
        parent_id: 4,
        name: "Follow Up",
        description: "Lead follow-up management",
        icon: "PhoneCall",
        path: "/sales/follow-ups",
        sort_order: 5,
        is_visible: true,
        string_id: "sales-follow-up",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 10,
        parent_id: 4,
        name: "Quotations",
        description: "Quotation management",
        icon: "FileText",
        path: "/sales/quotations",
        sort_order: 6,
        is_visible: true,
        string_id: "sales-quotations",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 11,
        parent_id: 4,
        name: "Approval Queue",
        description: "Pending approvals",
        icon: "Clock",
        path: "/sales/approval-queue",
        sort_order: 7,
        is_visible: true,
        string_id: "sales-approval-queue",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 12,
        parent_id: 4,
        name: "Rejected Quotes",
        description: "Rejected quotations",
        icon: "X",
        path: "/sales/rejected-quotes",
        sort_order: 8,
        is_visible: true,
        string_id: "sales-rejected-quotes",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 13,
        parent_id: 4,
        name: "Order Confirmation",
        description: "Order processing",
        icon: "Check",
        path: "/sales/orders",
        sort_order: 9,
        is_visible: true,
        string_id: "sales-order-confirmation",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 14,
        parent_id: 4,
        name: "Rejected Leads",
        description: "Rejected leads",
        icon: "XCircle",
        path: "/sales/rejected-leads",
        sort_order: 10,
        is_visible: true,
        string_id: "sales-rejected-leads",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 15,
        parent_id: 4,
        name: "Lead Sources",
        description: "Lead source tracking",
        icon: "Globe",
        path: "/sales/sources",
        sort_order: 11,
        is_visible: true,
        string_id: "sales-lead-sources",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 16,
        parent_id: 4,
        name: "🤖 AI Business Insights",
        description: "AI-powered analytics",
        icon: "Brain",
        path: "/sales/ai-insights",
        sort_order: 12,
        is_visible: true,
        string_id: "ai-business-insights",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 17,
        parent_id: 4,
        name: "📞 AI Call Analytics",
        description: "AI call analysis",
        icon: "Phone",
        path: "/sales/call-analytics",
        sort_order: 13,
        is_visible: true,
        string_id: "ai-call-analytics",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 18,
        parent_id: 4,
        name: "Team Performance",
        description: "Team metrics",
        icon: "TrendingUp",
        path: "/sales/team-performance",
        sort_order: 14,
        is_visible: true,
        string_id: "reports-team-performance",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 19,
        parent_id: 4,
        name: "Quotations Analytics",
        description: "Quotation analysis",
        icon: "PieChart",
        path: "/sales/quotations-analytics",
        sort_order: 15,
        is_visible: true,
        string_id: "sales-quotations-analytics",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 20,
        parent_id: 4,
        name: "Lead Source Analysis",
        description: "Lead source metrics",
        icon: "BarChart2",
        path: "/sales/lead-source-analysis",
        sort_order: 16,
        is_visible: true,
        string_id: "reports-lead-sources",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 21,
        parent_id: 4,
        name: "Conversion Funnel",
        description: "Conversion analysis",
        icon: "Filter",
        path: "/sales/conversion-funnel",
        sort_order: 17,
        is_visible: true,
        string_id: "reports-conversion-funnel",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // Organization Section
  {
    id: 22,
    name: "Organization",
    description: "Organization management",
    icon: "Building2",
    path: "/organization",
    sort_order: 3,
    is_visible: true,
    string_id: "organization",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 23,
        parent_id: 22,
        name: "Companies",
        description: "Company management",
        icon: "Building",
        path: "/organization/companies",
        sort_order: 1,
        is_visible: true,
        string_id: "organization-companies",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 24,
        parent_id: 22,
        name: "Branches",
        description: "Branch management",
        icon: "GitBranch",
        path: "/organization/branches",
        sort_order: 2,
        is_visible: true,
        string_id: "organization-branches",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 25,
        parent_id: 22,
        name: "Clients",
        description: "Client management",
        icon: "Users",
        path: "/organization/clients",
        sort_order: 3,
        is_visible: true,
        string_id: "organization-clients",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 26,
        parent_id: 22,
        name: "Suppliers",
        description: "Supplier management",
        icon: "Truck",
        path: "/organization/suppliers",
        sort_order: 4,
        is_visible: true,
        string_id: "organization-suppliers",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 27,
        parent_id: 22,
        name: "Vendors",
        description: "Vendor management",
        icon: "Store",
        path: "/organization/vendors",
        sort_order: 5,
        is_visible: true,
        string_id: "organization-vendors",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 28,
        parent_id: 22,
        name: "Roles & Permissions",
        description: "Access control",
        icon: "Shield",
        path: "/organization/roles",
        sort_order: 6,
        is_visible: true,
        string_id: "organization-roles",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 29,
        parent_id: 22,
        name: "User Accounts",
        description: "User management",
        icon: "User",
        path: "/organization/user-accounts",
        sort_order: 7,
        is_visible: true,
        string_id: "organization-user-accounts",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 30,
        parent_id: 22,
        name: "Account Creation",
        description: "Create new users",
        icon: "UserPlus",
        path: "/organization/accounts/create",
        sort_order: 8,
        is_visible: true,
        string_id: "organization-account-creation",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 31,
        parent_id: 22,
        name: "Menu Manager",
        description: "Menu management",
        icon: "Menu",
        path: "/organization/menu-manager",
        sort_order: 9,
        is_visible: true,
        string_id: "organization-menu-manager",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // People & HR Section
  {
    id: 32,
    name: "People & HR",
    description: "HR management",
    icon: "Users",
    path: "/people",
    sort_order: 4,
    is_visible: true,
    string_id: "people-hr",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 33,
        parent_id: 32,
        name: "People Dashboard",
        description: "HR analytics",
        icon: "BarChart",
        path: "/people/dashboard",
        sort_order: 1,
        is_visible: true,
        string_id: "people-dashboard",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 34,
        parent_id: 32,
        name: "Employees",
        description: "Employee management",
        icon: "User",
        path: "/people/employees",
        sort_order: 2,
        is_visible: true,
        string_id: "people-employees",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 35,
        parent_id: 32,
        name: "Departments",
        description: "Department management",
        icon: "Grid",
        path: "/people/departments",
        sort_order: 3,
        is_visible: true,
        string_id: "people-departments",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 36,
        parent_id: 32,
        name: "Designations",
        description: "Role designations",
        icon: "Award",
        path: "/people/designations",
        sort_order: 4,
        is_visible: true,
        string_id: "people-designations",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // Task Management Section
  {
    id: 37,
    name: "Task Management",
    description: "Task management",
    icon: "CheckSquare",
    path: "/tasks",
    sort_order: 5,
    is_visible: true,
    string_id: "task-management",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 38,
        parent_id: 37,
        name: "My Tasks",
        description: "Personal tasks",
        icon: "List",
        path: "/tasks/my-tasks",
        sort_order: 1,
        is_visible: true,
        string_id: "tasks-my-tasks",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 39,
        parent_id: 37,
        name: "Task Control Center",
        description: "Task oversight",
        icon: "Command",
        path: "/tasks/control-center",
        sort_order: 2,
        is_visible: true,
        string_id: "tasks-control-center",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 40,
        parent_id: 37,
        name: "AI Task Generator",
        description: "AI task creation",
        icon: "Cpu",
        path: "/tasks/ai-generator",
        sort_order: 3,
        is_visible: true,
        string_id: "tasks-ai-generator",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 41,
        parent_id: 37,
        name: "Task Analytics",
        description: "Task metrics",
        icon: "BarChart",
        path: "/tasks/analytics",
        sort_order: 4,
        is_visible: true,
        string_id: "tasks-analytics",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 42,
        parent_id: 37,
        name: "Task Calendar",
        description: "Task scheduling",
        icon: "Calendar",
        path: "/tasks/calendar",
        sort_order: 5,
        is_visible: true,
        string_id: "tasks-calendar",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 43,
        parent_id: 37,
        name: "Task Reports",
        description: "Task reporting",
        icon: "FileText",
        path: "/tasks/reports",
        sort_order: 6,
        is_visible: true,
        string_id: "tasks-reports",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 44,
        parent_id: 37,
        name: "Task Sequence Management",
        description: "Task workflow",
        icon: "GitBranch",
        path: "/tasks/sequences",
        sort_order: 7,
        is_visible: true,
        string_id: "tasks-sequence-management",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 45,
        parent_id: 37,
        name: "Integration Status",
        description: "System integration",
        icon: "Link2",
        path: "/tasks/integrations",
        sort_order: 8,
        is_visible: true,
        string_id: "tasks-integration-status",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // Accounting & Finance Section
  {
    id: 46,
    name: "Accounting & Finance",
    description: "Financial management",
    icon: "DollarSign",
    path: "/accounting",
    sort_order: 6,
    is_visible: true,
    string_id: "accounting-finance",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 47,
        parent_id: 46,
        name: "Financial Dashboard",
        description: "Financial overview",
        icon: "BarChart",
        path: "/accounting/dashboard",
        sort_order: 1,
        is_visible: true,
        string_id: "accounting-dashboard",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 48,
        parent_id: 46,
        name: "Invoices",
        description: "Invoice management",
        icon: "FileText",
        path: "/accounting/invoices",
        sort_order: 2,
        is_visible: true,
        string_id: "accounting-invoices",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 49,
        parent_id: 46,
        name: "Payments",
        description: "Payment processing",
        icon: "CreditCard",
        path: "/accounting/payments",
        sort_order: 3,
        is_visible: true,
        string_id: "accounting-payments",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 50,
        parent_id: 46,
        name: "Expenses",
        description: "Expense tracking",
        icon: "Receipt",
        path: "/accounting/expenses",
        sort_order: 4,
        is_visible: true,
        string_id: "accounting-expenses",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // Event Coordination Section
  {
    id: 51,
    name: "Event Coordination",
    description: "Event management",
    icon: "Calendar",
    path: "/events",
    sort_order: 7,
    is_visible: true,
    string_id: "event-coordination",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 52,
        parent_id: 51,
        name: "Events Dashboard",
        description: "Event overview",
        icon: "BarChart",
        path: "/events/dashboard",
        sort_order: 1,
        is_visible: true,
        string_id: "events-dashboard",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 53,
        parent_id: 51,
        name: "Event Calendar",
        description: "Event scheduling",
        icon: "Calendar",
        path: "/events/calendar",
        sort_order: 2,
        is_visible: true,
        string_id: "events-calendar",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 54,
        parent_id: 51,
        name: "Events",
        description: "Event management",
        icon: "Star",
        path: "/events/list",
        sort_order: 3,
        is_visible: true,
        string_id: "events",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 55,
        parent_id: 51,
        name: "Event Types",
        description: "Event categories",
        icon: "Tag",
        path: "/events/types",
        sort_order: 4,
        is_visible: true,
        string_id: "events-types",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 56,
        parent_id: 51,
        name: "Services",
        description: "Event services",
        icon: "Tool",
        path: "/events/services",
        sort_order: 5,
        is_visible: true,
        string_id: "events-services",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 57,
        parent_id: 51,
        name: "Venues",
        description: "Event venues",
        icon: "MapPin",
        path: "/events/venues",
        sort_order: 6,
        is_visible: true,
        string_id: "events-venues",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 58,
        parent_id: 51,
        name: "Staff Assignment",
        description: "Event staffing",
        icon: "Users",
        path: "/events/staff",
        sort_order: 7,
        is_visible: true,
        string_id: "events-staff",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // Post Production Section
  {
    id: 59,
    name: "Post Production",
    description: "Production management",
    icon: "Film",
    path: "/production",
    sort_order: 8,
    is_visible: true,
    string_id: "post-production",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 60,
        parent_id: 59,
        name: "Production Dashboard",
        description: "Production overview",
        icon: "BarChart",
        path: "/production/dashboard",
        sort_order: 1,
        is_visible: true,
        string_id: "post-production-dashboard",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 61,
        parent_id: 59,
        name: "Deliverables",
        description: "Project deliverables",
        icon: "Package",
        path: "/production/deliverables",
        sort_order: 2,
        is_visible: true,
        string_id: "post-production-deliverables",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 62,
        parent_id: 59,
        name: "Deliverables Workflow",
        description: "Delivery workflow",
        icon: "GitBranch",
        path: "/production/workflow",
        sort_order: 3,
        is_visible: true,
        string_id: "post-production-deliverables-workflow",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 63,
        parent_id: 59,
        name: "Projects",
        description: "Project management",
        icon: "Folder",
        path: "/production/projects",
        sort_order: 4,
        is_visible: true,
        string_id: "post-production-projects",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 64,
        parent_id: 59,
        name: "Workflow",
        description: "Process management",
        icon: "Shuffle",
        path: "/production/workflow-management",
        sort_order: 5,
        is_visible: true,
        string_id: "post-production-workflow",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 65,
        parent_id: 59,
        name: "Quality Control",
        description: "Quality assurance",
        icon: "CheckCircle",
        path: "/production/quality",
        sort_order: 6,
        is_visible: true,
        string_id: "post-production-quality",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 66,
        parent_id: 59,
        name: "Client Review",
        description: "Client feedback",
        icon: "Eye",
        path: "/production/client-review",
        sort_order: 7,
        is_visible: true,
        string_id: "post-production-review",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 67,
        parent_id: 59,
        name: "Final Delivery",
        description: "Project completion",
        icon: "Send",
        path: "/production/delivery",
        sort_order: 8,
        is_visible: true,
        string_id: "post-production-delivery",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // Post-Sales Section
  {
    id: 68,
    name: "Post-Sales",
    description: "Post-sales service",
    icon: "Handshake",
    path: "/post-sales",
    sort_order: 9,
    is_visible: true,
    string_id: "post-sales",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 69,
        parent_id: 68,
        name: "Post-Sales Dashboard",
        description: "Service overview",
        icon: "BarChart",
        path: "/post-sales/dashboard",
        sort_order: 1,
        is_visible: true,
        string_id: "post-sales-dashboard",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 70,
        parent_id: 68,
        name: "Delivery Management",
        description: "Delivery tracking",
        icon: "Truck",
        path: "/post-sales/delivery",
        sort_order: 2,
        is_visible: true,
        string_id: "post-sales-delivery",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 71,
        parent_id: 68,
        name: "Customer Support",
        description: "Customer service",
        icon: "Headphones",
        path: "/post-sales/support",
        sort_order: 3,
        is_visible: true,
        string_id: "post-sales-support",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 72,
        parent_id: 68,
        name: "Customer Feedback",
        description: "Feedback management",
        icon: "MessageSquare",
        path: "/post-sales/feedback",
        sort_order: 4,
        is_visible: true,
        string_id: "post-sales-feedback",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // Reports & Analytics Section
  {
    id: 73,
    name: "Reports & Analytics",
    description: "Business analytics",
    icon: "PieChart",
    path: "/reports",
    sort_order: 10,
    is_visible: true,
    string_id: "reports-analytics",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: [
      {
        id: 77,
        parent_id: 73,
        name: "Business Trends",
        description: "Trend analysis",
        icon: "LineChart",
        path: "/reports/trends",
        sort_order: 4,
        is_visible: true,
        string_id: "reports-trends",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 78,
        parent_id: 73,
        name: "Custom Reports",
        description: "Custom reporting",
        icon: "FileText",
        path: "/reports/custom",
        sort_order: 5,
        is_visible: true,
        string_id: "reports-custom",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      },
      {
        id: 80,
        parent_id: 73,
        name: "Customer Review",
        description: "",
        icon: "FileText",
        path: "/reports/customer-review",
        sort_order: 60,
        is_visible: true,
        string_id: "reports-customer-review",
        section_name: "Reports & Analytics",
        is_admin_only: false,
        badge_variant: "secondary",
        is_new: false,
        category: "primary"
      }
    ]
  },

  // System Administration Section
  {
    id: 79,
    name: "System Administration",
    description: "System administration",
    icon: "Settings",
    path: "/admin",
    sort_order: 11,
    is_visible: true,
    string_id: "system-administration",
    is_admin_only: false,
    badge_variant: "secondary",
    is_new: false,
    category: "primary",
    children: []
  }
]; 