import { MenuItem } from "@/types/menu"

export const menuItems: MenuItem[] = [
  {
    id: 1,
    parentId: null,
    name: "Dashboard",
    description: "View your dashboard",
    icon: "LayoutDashboard",
    path: "/dashboard",
    sortOrder: 1,
    isVisible: true,
  },
  {
    id: 2,
    parentId: null,
    name: "Organization",
    description: "Organization management",
    icon: "Building2",
    path: "/organization",
    sortOrder: 2,
    isVisible: true,
    children: [
      { id: 3, parentId: 2, name: "Companies", description: "Manage companies", icon: "Building", path: "/organization/companies", sortOrder: 1, isVisible: true },
      { id: 4, parentId: 2, name: "Branches", description: "Manage branches", icon: "GitBranch", path: "/organization/branches", sortOrder: 2, isVisible: true },
      { id: 5, parentId: 2, name: "Vendors", description: "Manage vendors", icon: "Package", path: "/organization/vendors", sortOrder: 3, isVisible: true },
      { id: 6, parentId: 2, name: "Suppliers", description: "Manage suppliers", icon: "Truck", path: "/organization/suppliers", sortOrder: 4, isVisible: true },
      { id: 7, parentId: 2, name: "Clients", description: "Manage clients", icon: "User", path: "/organization/clients", sortOrder: 5, isVisible: true },
      { id: 8, parentId: 2, name: "Roles", description: "Manage roles and permissions", icon: "Shield", path: "/organization/roles", sortOrder: 6, isVisible: true },
      { id: 9, parentId: 2, name: "User Accounts", description: "Manage user accounts", icon: "UserCog", path: "/organization/user-accounts", sortOrder: 7, isVisible: true },
      { id: 10, parentId: 2, name: "Account Creation", description: "Create new accounts", icon: "UserPlus", path: "/organization/account-creation", sortOrder: 8, isVisible: true },
    ],
  },
  {
    id: 11,
    parentId: null,
    name: "People",
    description: "People management",
    icon: "Users",
    path: "/people",
    sortOrder: 3,
    isVisible: true,
    children: [
      { id: 12, parentId: 11, name: "Dashboard", description: "People dashboard", icon: "LayoutDashboard", path: "/people/dashboard", sortOrder: 1, isVisible: true },
      { id: 13, parentId: 11, name: "Employees", description: "Manage employees", icon: "User", path: "/people/employees", sortOrder: 2, isVisible: true },
      { id: 14, parentId: 11, name: "Departments", description: "Manage departments", icon: "Building", path: "/people/departments", sortOrder: 3, isVisible: true },
      { id: 15, parentId: 11, name: "Designations", description: "Manage designations", icon: "Briefcase", path: "/people/designations", sortOrder: 4, isVisible: true },
    ],
  },
  {
    id: 16,
    parentId: null,
    name: "Sales",
    description: "Sales management",
    icon: "TrendingUp",
    path: "/sales",
    sortOrder: 4,
    isVisible: true,
    children: [
      { id: 17, parentId: 16, name: "Dashboard", description: "Sales dashboard", icon: "LayoutDashboard", path: "/sales/dashboard", sortOrder: 1, isVisible: true },
      { id: 18, parentId: 16, name: "Create Lead", description: "Create a new lead", icon: "PlusCircle", path: "/sales/create-lead", sortOrder: 2, isVisible: true },
      { id: 19, parentId: 16, name: "My Leads", description: "View my leads", icon: "List", path: "/sales/my-leads", sortOrder: 3, isVisible: true },
      { id: 20, parentId: 16, name: "Manage Lead", description: "Manage leads", icon: "ClipboardList", path: "/sales/manage-lead", sortOrder: 4, isVisible: true },
      { id: 21, parentId: 16, name: "Unassigned Lead", description: "Unassigned leads", icon: "UserPlus", path: "/sales/unassigned-lead", sortOrder: 5, isVisible: true },
      { id: 22, parentId: 16, name: "Lead Sources", description: "Lead sources", icon: "Link", path: "/sales/lead-sources", sortOrder: 6, isVisible: true },
      { id: 23, parentId: 16, name: "Follow Up", description: "Follow up on leads", icon: "CheckCircle", path: "/sales/follow-up", sortOrder: 7, isVisible: true },
      { id: 24, parentId: 16, name: "Quotation", description: "Create quotations", icon: "FileText", path: "/sales/quotation", sortOrder: 8, isVisible: true },
      { id: 25, parentId: 16, name: "Order Confirmation", description: "Order confirmations", icon: "CheckSquare", path: "/sales/order-confirmation", sortOrder: 9, isVisible: true },
      { id: 26, parentId: 16, name: "Rejected Leads", description: "Rejected leads", icon: "XCircle", path: "/sales/rejected-leads", sortOrder: 10, isVisible: true },
    ],
  },
  {
    id: 27,
    parentId: null,
    name: "Reports",
    description: "View reports",
    icon: "BarChart",
    path: "/reports",
    sortOrder: 5,
    isVisible: true,
    children: [
      { id: 28, parentId: 27, name: "Lead Sources", description: "Lead sources report", icon: "Link", path: "/reports/lead-sources", sortOrder: 1, isVisible: true },
      { id: 29, parentId: 27, name: "Sales Performance", description: "Sales performance report", icon: "TrendingUp", path: "/reports/sales-performance", sortOrder: 2, isVisible: true },
      { id: 30, parentId: 27, name: "Employee Performance", description: "Employee performance report", icon: "UserCheck", path: "/reports/employee-performance", sortOrder: 3, isVisible: true },
      { id: 31, parentId: 27, name: "Conversion Funnel", description: "Conversion funnel report", icon: "PieChart", path: "/reports/conversion-funnel", sortOrder: 4, isVisible: true },
      { id: 32, parentId: 27, name: "Team Performance", description: "Team performance report", icon: "Users", path: "/reports/team-performance", sortOrder: 5, isVisible: true },
      { id: 33, parentId: 27, name: "Trend Analysis", description: "Trend analysis report", icon: "BarChart2", path: "/reports/trend-analysis", sortOrder: 6, isVisible: true },
      { id: 34, parentId: 27, name: "Custom Reports", description: "Custom reports", icon: "FileText", path: "/reports/custom", sortOrder: 7, isVisible: true },
    ],
  },
  {
    id: 35,
    parentId: null,
    name: "Event Coordination",
    description: "Coordinate events",
    icon: "Calendar",
    path: "/event-coordination",
    sortOrder: 6,
    isVisible: true,
    children: [
      { id: 36, parentId: 35, name: "Events Dashboard", description: "Events dashboard", icon: "LayoutDashboard", path: "/event-coordination/dashboard", sortOrder: 1, isVisible: true },
      { id: 37, parentId: 35, name: "Event Calendar", description: "Event calendar", icon: "Calendar", path: "/event-coordination/calendar", sortOrder: 2, isVisible: true },
      { id: 38, parentId: 35, name: "Events", description: "Manage events", icon: "Calendar", path: "/event-coordination/events", sortOrder: 3, isVisible: true },
      { id: 39, parentId: 35, name: "Event Types", description: "Event types", icon: "ClipboardList", path: "/event-coordination/event-types", sortOrder: 4, isVisible: true },
      { id: 40, parentId: 35, name: "Venues", description: "Manage venues", icon: "MapPin", path: "/event-coordination/venues", sortOrder: 5, isVisible: true },
      { id: 41, parentId: 35, name: "Staff Assignment", description: "Assign staff to events", icon: "Users", path: "/event-coordination/staff-assignment", sortOrder: 6, isVisible: true },
    ],
  },
  {
    id: 42,
    parentId: null,
    name: "Audit",
    description: "Audit management",
    icon: "CheckCircle",
    path: "/audit",
    sortOrder: 7,
    isVisible: true,
    children: [
      { id: 43, parentId: 42, name: "Activity Logs", description: "View activity logs", icon: "ClipboardList", path: "/audit/activity-logs", sortOrder: 1, isVisible: true },
      { id: 44, parentId: 42, name: "Employee Audit", description: "Employee audit logs", icon: "UserCheck", path: "/audit/employee-audit", sortOrder: 2, isVisible: true },
    ],
  },
  {
    id: 45,
    parentId: null,
    name: "Admin",
    description: "Admin functions",
    icon: "Shield",
    path: "/admin",
    sortOrder: 8,
    isVisible: true,
    children: [
      { id: 46, parentId: 45, name: "Menu & Role Permissions", description: "Manage menu and role permissions", icon: "Lock", path: "/admin/menu-permissions", sortOrder: 1, isVisible: true },
    ],
  },
] 